/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedShipmentsRouteImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedCatalogProductIdRouteImport } from './routes/_authenticated/catalog_.$productId'
import { Route as AuthenticatedCustomersUserIdRouteImport } from './routes/_authenticated/customers_.$userId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated/orders_.$orderId'
import { Route as AuthenticatedPaymentsPaymentIdRouteImport } from './routes/_authenticated/payments_.$paymentId'
import { Route as AuthenticatedShipmentsShipmentIdRouteImport } from './routes/_authenticated/shipments_.$shipmentId'
import { Route as AuthenticatedPaymentsRunsRunIdRouteImport } from './routes/_authenticated/payments_.runs.$runId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShipmentsRoute = AuthenticatedShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCatalogProductIdRoute =
  AuthenticatedCatalogProductIdRouteImport.update({
    id: '/catalog_/$productId',
    path: '/catalog/$productId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersUserIdRoute =
  AuthenticatedCustomersUserIdRouteImport.update({
    id: '/customers_/$userId',
    path: '/customers/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders_/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsPaymentIdRoute =
  AuthenticatedPaymentsPaymentIdRouteImport.update({
    id: '/payments_/$paymentId',
    path: '/payments/$paymentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipmentsShipmentIdRoute =
  AuthenticatedShipmentsShipmentIdRouteImport.update({
    id: '/shipments_/$shipmentId',
    path: '/shipments/$shipmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsRunsRunIdRoute =
  AuthenticatedPaymentsRunsRunIdRouteImport.update({
    id: '/payments_/runs/$runId',
    path: '/payments/runs/$runId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/customers/$userId': typeof AuthenticatedCustomersUserIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/shipments/$shipmentId': typeof AuthenticatedShipmentsShipmentIdRoute
  '/payments/runs/$runId': typeof AuthenticatedPaymentsRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/shipments': typeof AuthenticatedShipmentsRoute
  '/': typeof AuthenticatedIndexRoute
  '/catalog/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/customers/$userId': typeof AuthenticatedCustomersUserIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/shipments/$shipmentId': typeof AuthenticatedShipmentsShipmentIdRoute
  '/payments/runs/$runId': typeof AuthenticatedPaymentsRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/catalog_/$productId': typeof AuthenticatedCatalogProductIdRoute
  '/_authenticated/customers_/$userId': typeof AuthenticatedCustomersUserIdRoute
  '/_authenticated/orders_/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/payments_/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/_authenticated/shipments_/$shipmentId': typeof AuthenticatedShipmentsShipmentIdRoute
  '/_authenticated/payments_/runs/$runId': typeof AuthenticatedPaymentsRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/catalog'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/payments'
    | '/shipments'
    | '/catalog/$productId'
    | '/customers/$userId'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/shipments/$shipmentId'
    | '/payments/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/catalog'
    | '/customers'
    | '/inventory'
    | '/orders'
    | '/payments'
    | '/shipments'
    | '/'
    | '/catalog/$productId'
    | '/customers/$userId'
    | '/orders/$orderId'
    | '/payments/$paymentId'
    | '/shipments/$shipmentId'
    | '/payments/runs/$runId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forbidden'
    | '/login'
    | '/_authenticated/catalog'
    | '/_authenticated/customers'
    | '/_authenticated/inventory'
    | '/_authenticated/orders'
    | '/_authenticated/payments'
    | '/_authenticated/shipments'
    | '/_authenticated/'
    | '/_authenticated/catalog_/$productId'
    | '/_authenticated/customers_/$userId'
    | '/_authenticated/orders_/$orderId'
    | '/_authenticated/payments_/$paymentId'
    | '/_authenticated/shipments_/$shipmentId'
    | '/_authenticated/payments_/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog_/$productId': {
      id: '/_authenticated/catalog_/$productId'
      path: '/catalog/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof AuthenticatedCatalogProductIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers_/$userId': {
      id: '/_authenticated/customers_/$userId'
      path: '/customers/$userId'
      fullPath: '/customers/$userId'
      preLoaderRoute: typeof AuthenticatedCustomersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders_/$orderId': {
      id: '/_authenticated/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments_/$paymentId': {
      id: '/_authenticated/payments_/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof AuthenticatedPaymentsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments_/$shipmentId': {
      id: '/_authenticated/shipments_/$shipmentId'
      path: '/shipments/$shipmentId'
      fullPath: '/shipments/$shipmentId'
      preLoaderRoute: typeof AuthenticatedShipmentsShipmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments_/runs/$runId': {
      id: '/_authenticated/payments_/runs/$runId'
      path: '/payments/runs/$runId'
      fullPath: '/payments/runs/$runId'
      preLoaderRoute: typeof AuthenticatedPaymentsRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCatalogProductIdRoute: typeof AuthenticatedCatalogProductIdRoute
  AuthenticatedCustomersUserIdRoute: typeof AuthenticatedCustomersUserIdRoute
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
  AuthenticatedPaymentsPaymentIdRoute: typeof AuthenticatedPaymentsPaymentIdRoute
  AuthenticatedShipmentsShipmentIdRoute: typeof AuthenticatedShipmentsShipmentIdRoute
  AuthenticatedPaymentsRunsRunIdRoute: typeof AuthenticatedPaymentsRunsRunIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCatalogProductIdRoute: AuthenticatedCatalogProductIdRoute,
  AuthenticatedCustomersUserIdRoute: AuthenticatedCustomersUserIdRoute,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
  AuthenticatedPaymentsPaymentIdRoute: AuthenticatedPaymentsPaymentIdRoute,
  AuthenticatedShipmentsShipmentIdRoute: AuthenticatedShipmentsShipmentIdRoute,
  AuthenticatedPaymentsRunsRunIdRoute: AuthenticatedPaymentsRunsRunIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
